class DotenvKeys:
    MODEL_DEFAULT_DIR = 'MODEL_DEFAULT_DIR'
    MUSIC_DIR = 'MUSIC_DIR'


class Songs:
    OLD_MCDONALD = "CCCGAAGGEEDDCCCGCCCGAAGGEEDDCCCG"
    TWINKLE_TWINKLE = "CCGGAAGGFFEEDDCCGGFFEEDDGGFFEEDDCCGGAAGGFFEEDDCC"
    ODE_TO_JOY = "EEFGGFEDCCDEEDDDEEFGGFEDCCDEDCCCDDECDFECDFEDCDGGEEFGGFEDCCDEDCC"
    HAPPY_BIRTHDAY = "GGAGCBGGAGDCGGGECBAFFECDC"
    ROW_YOUR_BOAT = "CCCDEEDEFGCCCGGGEEECCCGFEDC"
    JINGLE_BELLS = "CAGFCCCCAGFDDDDDBAGEEEECCBGAAAACAGFCCCCCAGFDDDDDBAGCCCCDCBGFAAAAAAAAACFGABBBBBAAAAGGAGGCCAAAAAAAAACFGAAAABBBBBAAACCBGF"
    TEST_SONG = "ABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABAB"
