from enum import Enum, auto


class SaveMode(Enum):
    NoSave = 'no-save'
    SaveLast = 'save-last'
    SaveBest = 'save-best'
    SaveEachNewBest = 'save-all-best'

    def __str__(self):
        return self.value

class SongPartitionMethod(Enum):
    NoPartition = auto(),
    AllSubstrings = auto(),


class DotenvKeys:
    MODEL_DEFAULT_DIR = 'MODEL_DEFAULT_DIR'
    MUSIC_DIR = 'MUSIC_DIR'

class Songs:
    TEST_SONG = "ABABABABABABABABABABABABABAB"
    OLD_MCDONALD = "CCCGAAGGEEDDCCCGCCCGAAGGEEDDCCCG"
    TWINKLE_TWINKLE = "CCGGAAGGFFEEDDCCGGFFEEDDGGFFEEDDCCGGAAGGFFEEDDCC"
    ODE_TO_JOY = "EEFGGFEDCCDEEDDDEEFGGFEDCCDEDCCCDDECDFECDFEDCDGGEEFGGFEDCCDEDCC"
    HAPPY_BIRTHDAY = "GGAGCBGGAGDCGGGECBAFFECDC"
    ROW_YOUR_BOAT = "CCCDEEDEFGCCCGGGEEECCCGFEDC"
    JINGLE_BELLS = "CAGFCCCCAGFDDDDDBAGEEEECCBGAAAACAGFCCCCCAGFDDDDDBAGCCCCDCBGFAAAAAAAAACFGABBBBBAAAAGGAGGCCAAAAAAAAACFGAAAABBBBBAAACCBGF"
